<a href="https://colab.research.google.com/github/Mumtahina-Ahmed-CSE/Chi-Square-Test-on-Medical-Data/blob/main/Chi_Square_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
!pip install bioinfokit

     |████████████████████████████████| 92kB 7.5MB/s 
  Created wheel for bioinfokit: filename=bioinfokit-2.0.2-cp37-none-any.whl size=56174 sha256=056b81f19761e02b61770c51be6c8e659fe86173e2b09238271412897187f44b
  Stored in directory: /root/.cache/pip/wheels/8e/3c/1d/369f28890a2139410deef43f69444d49bea2c37d3c3904a0fe
  Created wheel for adjustText: filename=adjustText-0.7.3-cp37-none-any.whl size=7100 sha256=441a4320efc3258f8ff6b953b5bebf008b15505a4b342a7c58471a1e504b39b0
  Stored in directory: /root/.cache/pip/wheels/41/95/74/7d347e136d672f8bc28e937032bc92baf4f80856763a7e7b72
Successfully built bioinfokit adjustText


In [9]:
import pandas as pd
# I am using interactive python interpreter (Python 3.7.4)
from bioinfokit.analys import stat, get_data
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/table.csv', header=0)
df.head()

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Index  HCW without COVID-19  HCW with COVID-19
0      0                   518                 83
1      1                   477                 75
2      2                   108                 17
3      3                    40                  5

In [10]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       518                 83
1                       477                 75
2                       108                 17
3                        40                  5

In [12]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            3      0.259814   0.9674
Log-likelihood     3      0.273289   0.964971



In [13]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0                519.231              81.7687
 1                476.898              75.102
 2                107.993              17.0068
 3                 38.8776              6.12245



In [14]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[518, 83], [477, 75], [108, 17], [40, 5]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(0.25981355275727247,
 0.9674003410009473,
 3,
 array([[519.23129252,  81.76870748],
        [476.89795918,  75.10204082],
        [107.99319728,  17.00680272],
        [ 38.87755102,   6.12244898]]))

In [15]:
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/table 2.csv', header=0)
df.head()

Index  HCW without COVID-19  HCW with COVID-19
0      0                   451                 71
1      1                   692                109

In [16]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       451                 71
1                       692                109

In [17]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            1    0.00619158   0.937282
Log-likelihood     1    0.00618752   0.937302



In [18]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0                  450.98              71.0204
 1                  692.02             108.98



In [19]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[451, 71], [692, 109]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(0.006191577914926582,
 0.9372819197730906,
 1,
 array([[450.97959184,  71.02040816],
        [692.02040816, 108.97959184]]))

In [21]:
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/table 3.csv', header=0)
df.head()

Index  HCW without COVID-19  HCW with COVID-19
0      0                   362                 57
1      1                   502                 79
2      2                     4                  8
3      3                    76                 12
4      4                   199                 24

In [22]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       362                 57
1                       502                 79
2                         4                  8
3                        76                 12
4                       199                 24

In [24]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square      P-value
--------------  ----  ------------  -----------
Pearson            4       30.2769  4.2984e-06
Log-likelihood     4       19.4436  0.000642914



In [25]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0                361.993              57.0068
 1                501.952              79.0476
 2                 10.3673              1.63265
 3                 76.0272             11.9728
 4                192.66               30.3401



In [26]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[362, 57], [502, 79], [4, 8], [76, 12], [199, 24]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(30.276946232306468,
 4.298402739269979e-06,
 4,
 array([[361.99319728,  57.00680272],
        [501.95238095,  79.04761905],
        [ 10.36734694,   1.63265306],
        [ 76.02721088,  11.97278912],
        [192.65986395,  30.34013605]]))