<a href="https://colab.research.google.com/github/Mumtahina-Ahmed-CSE/Chi-Square-Test-on-Medical-Data/blob/main/Chi_Square_Test_on_Medical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install bioinfokit

     |████████████████████████████████| 92kB 3.6MB/s 
  Created wheel for bioinfokit: filename=bioinfokit-2.0.2-cp37-none-any.whl size=56174 sha256=331f9f0daa45fb54a4262eaa414030cbbb64085a68d56b8ebca8c16b1691a83f
  Stored in directory: /root/.cache/pip/wheels/8e/3c/1d/369f28890a2139410deef43f69444d49bea2c37d3c3904a0fe
  Created wheel for adjustText: filename=adjustText-0.7.3-cp37-none-any.whl size=7100 sha256=e06d7188eaa44c7a9055f8d1a175c5951624b028311854651c10980db2ea47ba
  Stored in directory: /root/.cache/pip/wheels/41/95/74/7d347e136d672f8bc28e937032bc92baf4f80856763a7e7b72
Successfully built bioinfokit adjustText


In [4]:
import pandas as pd
# I am using interactive python interpreter (Python 3.7.4)
from bioinfokit.analys import stat, get_data
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Table1.csv', header=0)
df.head()

Index  HCW without COVID-19  HCW with COVID-19
0      0                   498                 83
1      1                   479                 67
2      2                   115                 24
3      3                    51                  6

In [5]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       498                 83
1                       479                 67
2                       115                 24
3                        51                  6

In [6]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            3       3.10032   0.376415
Log-likelihood     3       3.04893   0.384142



In [7]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0                501.952               79.0476
 1                471.714               74.2857
 2                120.088               18.9116
 3                 49.2449               7.7551



In [8]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[498, 83], [479, 67], [115, 24], [51, 6]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(3.1003172437344215,
 0.3764153547049384,
 3,
 array([[501.95238095,  79.04761905],
        [471.71428571,  74.28571429],
        [120.08843537,  18.91156463],
        [ 49.24489796,   7.75510204]]))

In [9]:
import pandas as pd
# I am using interactive python interpreter (Python 3.7.4)
from bioinfokit.analys import stat, get_data
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Table2.csv', header=0)
df.head()

Index  HCW without COVID-19  HCW with COVID-19
0      0                   389                 76
1      1                   754                104

In [10]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       389                 76
1                       754                104

In [11]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            1       4.22286  0.0398829
Log-likelihood     1       4.13361  0.0420395



In [12]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0                 401.735              63.2653
 1                 741.265             116.735



In [13]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[389, 76], [754, 104]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(4.222860851683243,
 0.03988286250132268,
 1,
 array([[401.73469388,  63.26530612],
        [741.26530612, 116.73469388]]))

In [14]:
import pandas as pd
# I am using interactive python interpreter (Python 3.7.4)
from bioinfokit.analys import stat, get_data
# load example dataset
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Table3.csv', header=0)
df.head()

Index  HCW without COVID-19  HCW with COVID-19
0      0                   362                 67
1      1                   502                 89
2      2                     4                  5
3      3                    76                  7
4      4                   199                 12

In [15]:
df = df.set_index('Index')
# output
df.head()

HCW without COVID-19  HCW with COVID-19
Index                                         
0                       362                 67
1                       502                 89
2                         4                  5
3                        76                  7
4                       199                 12

In [16]:
# run chi-square test for independence
res = stat()
res.chisq(df=df)
# output
print(res.summary)
# corrected for the Yates’ continuity


Chi-squared test for independence

Test              Df    Chi-square      P-value
--------------  ----  ------------  -----------
Pearson            4       29.1584  7.25902e-06
Log-likelihood     4       27.3141  1.71739e-05



In [17]:
print(res.expected_df)


Expected frequency counts

      HCW without COVID-19    HCW with COVID-19
--  ----------------------  -------------------
 0               370.633               58.3673
 1               510.592               80.4082
 2                 7.77551              1.22449
 3                71.7075              11.2925
 4               182.293               28.7075



In [18]:
# using chi2_contingency function from scipy package
import numpy as np
from scipy.stats import chi2_contingency 
# using Pearson’s chi-squared statistic
# corrected for the Yates’ continuity
observed = np.array([[362, 67], [502, 89], [4, 5], [76, 7], [199, 12]])
chi_val, p_val, dof, expected =  chi2_contingency(observed)
chi_val, p_val, dof, expected

(29.158406164215954,
 7.259016598671466e-06,
 4,
 array([[370.63265306,  58.36734694],
        [510.59183673,  80.40816327],
        [  7.7755102 ,   1.2244898 ],
        [ 71.70748299,  11.29251701],
        [182.29251701,  28.70748299]]))